// clang-format off
// This file is auto-generated by gen-strings.py. DO NOT EDIT.

#include "strings.h"

//
// macros & constants
//

#define zv_init(STR) {STR, c_litstrlen(STR)}

//
// global state
//

const zsview g_strings[1][43] = {
  [LOCALE_EN_US] = {
    [SID_AXIS_COUNT] = zv_init("Axis Count"),
    [SID_BALL_COUNT] = zv_init("Ball Count"),
    [SID_BATTERY] = zv_init("Battery"),
    [SID_BUTTON_COUNT] = zv_init("Button Count"),
    [SID_CACHE_LINE_SIZE] = zv_init("Cache Line Size"),
    [SID_CAP_DETAILS] = zv_init("DETAILS"),
    [SID_CAP_HARDWARE] = zv_init("HARDWARE"),
    [SID_CAP_OS] = zv_init("OS"),
    [SID_CAP_PROPERTIES] = zv_init("PROPERTIES"),
    [SID_CAP_SDL] = zv_init("SDL"),
    [SID_CONNECTION_TYPE] = zv_init("Connection Type"),
    [SID_CONTROLLERS] = zv_init("Controllers"),
    [SID_CONTROLLER_INFO] = zv_init("Controller Info"),
    [SID_CPU_CORES] = zv_init("CPU Cores"),
    [SID_FIRMWARE_VERSION] = zv_init("Firmware Version"),
    [SID_GAMEPAD_NAME] = zv_init("Gamepad Name"),
    [SID_GAMEPAD_TYPE] = zv_init("Gamepad Type"),
    [SID_GUID] = zv_init("GUID"),
    [SID_HAPTIC] = zv_init("Haptic"),
    [SID_INSTANCE_ID] = zv_init("Instance ID"),
    [SID_JOYSTICK_NAME] = zv_init("Joystick Name"),
    [SID_JOYSTICK_TYPE] = zv_init("Joystick Type"),
    [SID_LEFT_JOYSTICK] = zv_init("Left Joystick"),
    [SID_LEFT_TRIGGER] = zv_init("Left Trigger"),
    [SID_LOCALE_DISPLAY_NAME] = zv_init("English"),
    [SID_LOCALE_TAG] = zv_init("en-US"),
    [SID_PATH] = zv_init("Path"),
    [SID_PLATFORM] = zv_init("Platform"),
    [SID_POV_HAT_COUNT] = zv_init("POV Hat Count"),
    [SID_POWER_STATE] = zv_init("Power State"),
    [SID_PRODUCT] = zv_init("Product"),
    [SID_PRODUCT_VERSION] = zv_init("Product Version"),
    [SID_REVISION] = zv_init("Revision"),
    [SID_RIGHT_JOYSTICK] = zv_init("Right Joystick"),
    [SID_RIGHT_TRIGGER] = zv_init("Right Trigger"),
    [SID_SERIAL_NUMBER] = zv_init("Serial Number"),
    [SID_STEAM_ID] = zv_init("Steam ID"),
    [SID_SYSTEM] = zv_init("System"),
    [SID_SYSTEM_RAM] = zv_init("System RAM"),
    [SID_THEME] = zv_init("Theme"),
    [SID_TOUCHPAD_COUNT] = zv_init("Touchpad Count"),
    [SID_VENDOR] = zv_init("Vendor"),
    [SID_VERSION] = zv_init("Version"),
  },
};

//
// public function implementations
//

const char* GetString(Locale locale, StringID id)
{
  return g_strings[locale][id].str;
}

zsview GetStringView(Locale locale, StringID id)
{
  return g_strings[locale][id];
}
// clang-format on
