// clang-format off
// This file is auto-generated by gen-strings.py. DO NOT EDIT.

#include "strings.h"

//
// macros & constants
//

#define zv_init(STR) {STR, c_litstrlen(STR)}

//
// global state
//

const zsview g_strings[1][3] = {
  [LOCALE_EN_US] = {
    [SID_CONTROLLERS] = zv_init("Controllers"),
    [SID_LOCALE_DISPLAY_NAME] = zv_init("English"),
    [SID_LOCALE_TAG] = zv_init("en-US"),
  },
};

//
// public function implementations
//

zsview GetString(Locale locale, StringID id)
{
  return g_strings[locale][id];
}
// clang-format on
