// clang-format off
// This file is auto-generated by gen-strings.py. DO NOT EDIT.

#ifndef SDLI_STRINGS_H
#define SDLI_STRINGS_H

#include <stc/zsview.h>

//
// macros & constants
//

#define ICON_GAMEPAD "\xef\x84\x9b"
#define ICON_COG_ALT "\xee\xa0\x80"
#define ICON_WRENCH "\xee\xa0\x81"
#define ICON_BATTERY_4 "\xef\x89\x80"
#define ICON_BATTERY_3 "\xef\x89\x81"
#define ICON_BATTERY_2 "\xef\x89\x82"
#define ICON_BATTERY_1 "\xef\x89\x83"
#define ICON_BATTERY_0 "\xef\x89\x84"
#define ICON_UP_OUTLINE "\xee\xa0\x82"
#define ICON_RIGHT_OUTLINE "\xee\xa0\x83"
#define ICON_LEFT_OUTLINE "\xee\xa0\x84"
#define ICON_DOWN_OUTLINE "\xee\xa0\x85"
#define ICON_UP "\xee\xa0\x86"
#define ICON_RIGHT "\xee\xa0\x87"
#define ICON_LEFT "\xee\xa0\x88"
#define ICON_DOWN "\xee\xa0\x89"

//
// types
//

typedef enum Locale {
  LOCALE_EN_US,
  LOCALE__COUNT,
} Locale;

typedef enum StringID {
  SID_CONTROLLERS,
  SID_LOCALE_DISPLAY_NAME,
  SID_LOCALE_TAG,
  SID__COUNT,
} StringID;

//
// public functions
//

const char* GetString(Locale locale, StringID id);
zsview      GetStringView(Locale locale, StringID id);

#endif  // SDLI_STRINGS_H
// clang-format on
