#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( dirname "$SCRIPT_DIR" )"

# generates src/assets/assets.c
#
# Font and image files from the assets directory are piped through xxd to
# generate C source code of the binary. The C source is put into
# src/assets/assets.c. src/assets/assets.h contains the corresponding
# declarations.

dump_file() {
  echo "// font file: ${1}"
  echo ""
  # use const and std C types (assets.h includes stdint.h and stddef.h)
  cat "${ROOT_DIR}/${1}" | xxd -i -n "${2}" | sed -e 's/^unsigned char /const uint8_t /' -e 's/^unsigned int /const size_t /'
}

{
  echo "// This file is generated by scripts/gen-assets-c.sh. Do not edit."
  echo "#include \"assets.h\""
  echo ""

  dump_file "assets/fonts/roboto-regular.ttf" "asset_font_regular_ttf"
  dump_file "assets/fonts/roboto-bold.ttf" "asset_font_bold_ttf"
  dump_file "assets/fonts/fontello.ttf" "asset_font_icon_ttf"
  dump_file "assets/images/sdli_logo_w64.bmp" "asset_image_sdli_logo_w64_bmp"
} > "${ROOT_DIR}/src/assets/assets.c"
