#!/usr/bin/env python3

"""
Generate SDL Insight localized strings

This script creates src/sdli/strings.h|c containing localized strings and icon
font character strings. The localized strings are sourced from
assets/strings/<locale-tag>.json and the icon strings are taken from the
fontello config file (https://fontello.com/) from assets/fonts/fontello/config.json.
"""

import json
from pathlib import Path
import sys

# -- Configuration --
SCRIPT_PATH = Path(__file__).resolve()
SRC_ROOT = SCRIPT_PATH.parent.parent
FONTELLO_DIR = SRC_ROOT / "assets" / "fonts"
STRINGS_DIR = SRC_ROOT / "assets" / "strings"
GEN_DIR = SRC_ROOT / "src" / "sdli"

FONTELLO_CONFIG_PATH = FONTELLO_DIR / "config.json"

OUTPUT_HEADER_PATH = GEN_DIR / "strings.h"
OUTPUT_STRINGS_SOURCE_PATH = GEN_DIR / "strings.c"

# --- Helper Functions ---

def file_intro(out):
    out.write("// clang-format off\n")
    out.write(f"// This file is auto-generated by {SCRIPT_PATH.name}. DO NOT EDIT.\n\n")

def to_c_identifier(name):
    """Converts a string to a valid C identifier (uppercase)."""
    return name.upper().replace('-', '_').replace('(', '').replace(')', '')


def to_c_locale_identifier(tag):
    return f"LOCALE_{to_c_identifier(tag)}"


def to_string_id(key):
    return f"SID_{to_c_identifier(key)}"


def codepoint_to_utf8_cstr(codepoint):
    """Converts a Unicode codepoint to a C string literal of its UTF-8 bytes."""
    utf8_bytes = chr(codepoint).encode('utf-8')
    return "".join([f"\\x{b:02x}" for b in utf8_bytes])

def string_to_utf8_cstr(string):
    """Converts a string to a C string literal of its UTF-8 bytes."""
    utf8_bytes = string.encode('utf-8')
    result = []
    last_was_hex = False
    for b in utf8_bytes:
        # Printable ASCII range: space (32) to tilde (126)
        if 32 <= b <= 126:
            c = chr(b)
            # If previous was hex escape and current is hex digit, we must escape to avoid ambiguity
            if last_was_hex and c in "0123456789abcdefABCDEF":
                result.append(f"\\x{b:02x}")
                last_was_hex = True
            else:
                if c == '"':
                    result.append('\\"')
                elif c == '\\':
                    result.append('\\\\')
                else:
                    result.append(c)
                last_was_hex = False
        else:
            result.append(f"\\x{b:02x}")
            last_was_hex = True
    return "".join(result)

# add limited jsonc support (single line comments, no trailing comments).
class JSONWithCommentsDecoder(json.JSONDecoder):
    def __init__(self, **kw):
        super().__init__(**kw)

    def decode(self, s: str):
        s = '\n'.join(l if not l.lstrip().startswith('//') else '' for l in s.split('\n'))
        return super().decode(s)


# --- Main Logic ---

def main():
    """Main function to generate asset files."""
    print("Asset generator running.")
    print(f"Source Root: {SRC_ROOT}")
    print(f"Strings Dir:  {STRINGS_DIR}")
    print(f"gen Dir:   {GEN_DIR}")

    # Ensure build directory exists
    GEN_DIR.mkdir(exist_ok=True)

    # --- Load configuration files ---
    try:
        # TODO: get path from assets.json
        with open(FONTELLO_CONFIG_PATH, 'r', encoding='utf-8') as f:
            fontello_config = json.load(f, cls=JSONWithCommentsDecoder)
    except FileNotFoundError:
        print(f"Error: Configuration file not found at '{FONTELLO_CONFIG_PATH}'", file=sys.stderr)
        return 1

    # --- Load locale string files ---
    locales_data = {}
    print(f"Scanning for locale files in {STRINGS_DIR}...")
    if STRINGS_DIR.exists() and STRINGS_DIR.is_dir():
        for json_path in STRINGS_DIR.glob('*.json'):
            locale_tag = json_path.stem # e.g., "en-US" from "en-US.json"
            try:
                with open(json_path, 'r', encoding='utf-8') as f:
                    locales_data[locale_tag] = json.load(f, cls=JSONWithCommentsDecoder)
                    print(f"  Loaded locale: {locale_tag}")
            except json.JSONDecodeError as e:
                print(f"Error: Failed to parse JSON from '{json_path}': {e}", file=sys.stderr)
                return 1
            except Exception as e:
                print(f"Error: Could not read file '{json_path}': {e}", file=sys.stderr)
                return 1
    else:
        print(f"Warning: Strings directory not found at '{STRINGS_DIR}', skipping locale generation.")

    if not locales_data:
        print(f"Error: No locale files found in: {STRINGS_DIR}", file=sys.stderr)
        return 1

    if "en-US" not in locales_data:
        print(f"Error: No en-US locale file found in {STRINGS_DIR}", file=sys.stderr)
        return 1

    ordered_locale_tags = ['en-US'] + sorted([key for key in locales_data.keys() if key != 'en-US'])

    # -- Verify locale string consistency --
    print("Verifying locale string consistency...")
    # Use en-US as the reference for key structure
    reference_tag = "en-US"
    reference_data = locales_data[reference_tag]
    reference_keys = set(reference_data.keys())
    sorted_reference_keys = sorted(list(reference_keys))

    has_errors = False
    # Compare all other locales against the reference
    for locale_tag, data in locales_data.items():
        if locale_tag == reference_tag:
            continue

        current_keys = set(data.keys())
        missing = sorted(list(reference_keys - current_keys))
        extra = sorted(list(current_keys - reference_keys))

        if extra:
            print(f"Error: Locale '{locale_tag}' has extra keys not in '{reference_tag}'.", file=sys.stderr)
            print(f"  Extra keys: {', '.join(extra)}", file=sys.stderr)
            has_errors = True

        if missing:
            print(f"Warning: Locale '{locale_tag}' is missing keys from '{reference_tag}'.", file=sys.stderr)
            print(f"  Missing keys: {', '.join(missing)}", file=sys.stderr)
            print(f"  Using '{reference_tag}' values as fallback.", file=sys.stderr)

    if has_errors:
        return 1
    print("  Locale consistency check complete.")

    # -- strings.h --
    print(f"Generating {OUTPUT_HEADER_PATH}...")
    with open(OUTPUT_HEADER_PATH, 'w', encoding='utf-8', newline='\n') as f_h:
        file_intro(f_h)
        f_h.write('#ifndef SDLI_STRINGS_H\n')
        f_h.write('#define SDLI_STRINGS_H\n')
        f_h.write("\n")
        f_h.write("#include <stc/zsview.h>\n\n")

        f_h.write("//\n")
        f_h.write("// macros & constants\n")
        f_h.write("//\n\n")

        for glyph in fontello_config.get('glyphs', []):
            name = to_c_identifier(glyph['css'])
            f_h.write(f'#define ICON_{name} "{codepoint_to_utf8_cstr(glyph['code'])}"\n')
        f_h.write("\n")

        f_h.write("//\n")
        f_h.write("// types\n")
        f_h.write("//\n\n")

        f_h.write("typedef enum Locale {\n")
        for tag in ordered_locale_tags:
            f_h.write(f'  {to_c_locale_identifier(tag)},\n')
        f_h.write('  LOCALE__COUNT,\n')
        f_h.write("} Locale;\n\n")

        f_h.write("typedef enum StringID {\n")
        for key in sorted_reference_keys:
            f_h.write(f"  {to_string_id(key)},\n")
        f_h.write('  SID__COUNT,\n')
        f_h.write("} StringID;\n\n")

        f_h.write("//\n")
        f_h.write("// public functions\n")
        f_h.write("//\n\n")

        f_h.write("const char* GetString(Locale locale, StringID id);\n")
        f_h.write("zsview      GetStringView(Locale locale, StringID id);\n")
        f_h.write("// TODO: put this in the app?\n")
        f_h.write("#define STR(SID) GetString(LOCALE_EN_US, SID)\n")
        f_h.write("\n")

        f_h.write('#endif  // SDLI_STRINGS_H\n')
        f_h.write("// clang-format on\n")

    # -- strings.c --
    print(f"Generating {OUTPUT_STRINGS_SOURCE_PATH}...")
    with open(OUTPUT_STRINGS_SOURCE_PATH, 'w', encoding='utf-8', newline='\n') as f_c:
        file_intro(f_c)
        f_c.write('#include "strings.h"\n\n')

        f_c.write("//\n")
        f_c.write("// macros & constants\n")
        f_c.write("//\n\n")

        f_c.write("#define zv_init(STR) {STR, (isize)(sizeof(\"\" STR) - 1)}\n\n")

        f_c.write("//\n")
        f_c.write("// global state\n")
        f_c.write("//\n\n")

        f_c.write(f"const zsview g_strings[{len(ordered_locale_tags)}][{len(sorted_reference_keys)}] = {{\n")

        for tag in ordered_locale_tags:
            f_c.write(f"  [{to_c_locale_identifier(tag)}] = {{\n")
            for key in sorted_reference_keys:
                # Use locale-specific value if it exists, otherwise fallback to reference (en-US)
                value = locales_data.get(tag).get(key, reference_data[key])
                f_c.write(f'    [{to_string_id(key)}] = zv_init("{string_to_utf8_cstr(value)}"),\n')
            f_c.write('  },\n')
        f_c.write('};\n\n')

        f_c.write("//\n")
        f_c.write("// public function implementations\n")
        f_c.write("//\n\n")

        f_c.write('const char* GetString(Locale locale, StringID id)\n')
        f_c.write('{\n')
        f_c.write("  return g_strings[locale][id].str;\n")
        f_c.write("}\n\n")

        f_c.write('zsview GetStringView(Locale locale, StringID id)\n')
        f_c.write('{\n')
        f_c.write("  return g_strings[locale][id];\n")
        f_c.write("}\n")
        f_c.write("// clang-format on\n")

    print("Asset generation complete.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
